name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        sudo pip install pyinstaller
        sudo pip install --upgrade pyinstaller
        sudo pip install pyinstaller-versionfile
    - name: Build binary
      run: |
        pyinstaller --noconfirm --clean --noconfirm --onefile --nowindow --distpath=.dist/ --workpath=/tmp  src/data_analysis.py
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      run: >-
        gh release create ${{ github.ref_name }} ${{ github.workspace }}/dist/* --generate-notes --title "Version ${{ github.ref_name }}"